defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost

development:
  database: doomhub
  <<: *defaults

test:
  database: doomhub_test
  <<: *defaults

production:
  database: doomhub_prod
  <<: *defaults
